export interface GeoRole {
  id: string;
  title: string;
  category: 'engineering' | 'product' | 'design' | 'marketing' | 'sales' | 'operations' | 'finance' | 'people';
  medianUsdRemote: string;
  rangeUsdRemote: string;
  medianInrIndia?: string;
  rangeInrIndia?: string;
  topSkills: string[];
  searchKeywords: string[];
}

export const GEO_ROLES: GeoRole[] = [
  { id: 'software-engineer', title: 'Software Engineer', category: 'engineering', medianUsdRemote: '$145,000', rangeUsdRemote: '$118k–$185k', medianInrIndia: '₹28 LPA', rangeInrIndia: '₹18–45 LPA', topSkills: ['TypeScript', 'Python', 'system design', 'APIs', 'Git'], searchKeywords: ['remote software engineer', 'remote developer jobs'] },
  { id: 'frontend-developer', title: 'Frontend Developer', category: 'engineering', medianUsdRemote: '$135,000', rangeUsdRemote: '$105k–$170k', medianInrIndia: '₹22 LPA', rangeInrIndia: '₹14–38 LPA', topSkills: ['React', 'TypeScript', 'CSS', 'accessibility', 'performance'], searchKeywords: ['remote frontend developer', 'remote react jobs'] },
  { id: 'backend-developer', title: 'Backend Developer', category: 'engineering', medianUsdRemote: '$142,000', rangeUsdRemote: '$115k–$180k', medianInrIndia: '₹26 LPA', rangeInrIndia: '₹16–42 LPA', topSkills: ['Node.js', 'PostgreSQL', 'API design', 'cloud', 'security'], searchKeywords: ['remote backend developer', 'remote node jobs'] },
  { id: 'full-stack-developer', title: 'Full Stack Developer', category: 'engineering', medianUsdRemote: '$140,000', rangeUsdRemote: '$112k–$175k', medianInrIndia: '₹24 LPA', rangeInrIndia: '₹15–40 LPA', topSkills: ['React', 'Node', 'SQL', 'DevOps basics', 'testing'], searchKeywords: ['remote full stack developer', 'remote full stack jobs'] },
  { id: 'devops-engineer', title: 'DevOps Engineer', category: 'engineering', medianUsdRemote: '$150,000', rangeUsdRemote: '$125k–$190k', medianInrIndia: '₹30 LPA', rangeInrIndia: '₹20–48 LPA', topSkills: ['AWS', 'Kubernetes', 'CI/CD', 'Terraform', 'observability'], searchKeywords: ['remote devops engineer', 'remote sre jobs'] },
  { id: 'data-scientist', title: 'Data Scientist', category: 'engineering', medianUsdRemote: '$148,000', rangeUsdRemote: '$120k–$185k', medianInrIndia: '₹25 LPA', rangeInrIndia: '₹16–40 LPA', topSkills: ['Python', 'SQL', 'ML', 'statistics', 'experimentation'], searchKeywords: ['remote data scientist', 'remote ML jobs'] },
  { id: 'machine-learning-engineer', title: 'Machine Learning Engineer', category: 'engineering', medianUsdRemote: '$165,000', rangeUsdRemote: '$135k–$210k', medianInrIndia: '₹32 LPA', rangeInrIndia: '₹22–55 LPA', topSkills: ['PyTorch', 'LLMs', 'MLOps', 'Python', 'data pipelines'], searchKeywords: ['remote machine learning engineer', 'remote AI engineer jobs'] },
  { id: 'qa-engineer', title: 'QA Engineer', category: 'engineering', medianUsdRemote: '$115,000', rangeUsdRemote: '$90k–$145k', medianInrIndia: '₹14 LPA', rangeInrIndia: '₹8–22 LPA', topSkills: ['test automation', 'Playwright', 'CI', 'API testing', 'regression'], searchKeywords: ['remote QA engineer', 'remote test automation jobs'] },
  { id: 'mobile-developer', title: 'Mobile Developer', category: 'engineering', medianUsdRemote: '$138,000', rangeUsdRemote: '$110k–$172k', medianInrIndia: '₹22 LPA', rangeInrIndia: '₹14–36 LPA', topSkills: ['React Native', 'Swift', 'Kotlin', 'app performance', 'release cycles'], searchKeywords: ['remote mobile developer', 'remote ios android jobs'] },
  { id: 'cloud-architect', title: 'Cloud Architect', category: 'engineering', medianUsdRemote: '$175,000', rangeUsdRemote: '$145k–$220k', medianInrIndia: '₹38 LPA', rangeInrIndia: '₹28–60 LPA', topSkills: ['AWS', 'Azure', 'security', 'cost optimization', 'architecture'], searchKeywords: ['remote cloud architect', 'remote solutions architect jobs'] },
  { id: 'cybersecurity-analyst', title: 'Cybersecurity Analyst', category: 'engineering', medianUsdRemote: '$130,000', rangeUsdRemote: '$105k–$165k', medianInrIndia: '₹20 LPA', rangeInrIndia: '₹12–32 LPA', topSkills: ['SIEM', 'incident response', 'compliance', 'cloud security', 'threat modeling'], searchKeywords: ['remote cybersecurity analyst', 'remote security engineer jobs'] },
  { id: 'product-manager', title: 'Product Manager', category: 'product', medianUsdRemote: '$138,000', rangeUsdRemote: '$112k–$172k', medianInrIndia: '₹24 LPA', rangeInrIndia: '₹16–40 LPA', topSkills: ['roadmaps', 'discovery', 'metrics', 'stakeholders', 'async comms'], searchKeywords: ['remote product manager', 'remote PM jobs'] },
  { id: 'product-designer', title: 'Product Designer', category: 'design', medianUsdRemote: '$125,000', rangeUsdRemote: '$98k–$155k', medianInrIndia: '₹20 LPA', rangeInrIndia: '₹12–32 LPA', topSkills: ['Figma', 'UX research', 'prototyping', 'design systems', 'handoff'], searchKeywords: ['remote product designer', 'remote UX designer jobs'] },
  { id: 'ux-designer', title: 'UX Designer', category: 'design', medianUsdRemote: '$118,000', rangeUsdRemote: '$92k–$148k', medianInrIndia: '₹18 LPA', rangeInrIndia: '₹10–28 LPA', topSkills: ['user research', 'wireframes', 'usability', 'Figma', 'accessibility'], searchKeywords: ['remote UX designer', 'remote UI UX jobs'] },
  { id: 'graphic-designer', title: 'Graphic Designer', category: 'design', medianUsdRemote: '$75,000', rangeUsdRemote: '$55k–$95k', medianInrIndia: '₹8 LPA', rangeInrIndia: '₹5–14 LPA', topSkills: ['brand', 'Adobe CC', 'motion basics', 'marketing assets', 'templates'], searchKeywords: ['remote graphic designer', 'remote creative jobs'] },
  { id: 'marketing-manager', title: 'Marketing Manager', category: 'marketing', medianUsdRemote: '$105,000', rangeUsdRemote: '$82k–$132k', medianInrIndia: '₹16 LPA', rangeInrIndia: '₹10–26 LPA', topSkills: ['growth', 'content', 'analytics', 'campaigns', 'positioning'], searchKeywords: ['remote marketing manager', 'remote growth jobs'] },
  { id: 'content-writer', title: 'Content Writer', category: 'marketing', medianUsdRemote: '$72,000', rangeUsdRemote: '$50k–$92k', medianInrIndia: '₹7 LPA', rangeInrIndia: '₹4–12 LPA', topSkills: ['SEO writing', 'editing', 'research', 'B2B SaaS', 'async drafts'], searchKeywords: ['remote content writer', 'remote copywriter jobs'] },
  { id: 'seo-specialist', title: 'SEO Specialist', category: 'marketing', medianUsdRemote: '$78,000', rangeUsdRemote: '$58k–$98k', medianInrIndia: '₹9 LPA', rangeInrIndia: '₹6–15 LPA', topSkills: ['technical SEO', 'content strategy', 'Analytics', 'Search Console', 'link building'], searchKeywords: ['remote SEO specialist', 'remote SEO jobs'] },
  { id: 'sales-development-representative', title: 'Sales Development Representative', category: 'sales', medianUsdRemote: '$65,000', rangeUsdRemote: '$48k–$85k', medianInrIndia: '₹6 LPA', rangeInrIndia: '₹4–10 LPA', topSkills: ['outbound', 'CRM', 'sequences', 'qualification', 'calls'], searchKeywords: ['remote SDR', 'remote sales development jobs'] },
  { id: 'account-executive', title: 'Account Executive', category: 'sales', medianUsdRemote: '$95,000', rangeUsdRemote: '$70k–$130k', medianInrIndia: '₹12 LPA', rangeInrIndia: '₹8–22 LPA', topSkills: ['closing', 'discovery', 'demos', 'pipeline', 'SaaS sales'], searchKeywords: ['remote account executive', 'remote AE jobs'] },
  { id: 'customer-success-manager', title: 'Customer Success Manager', category: 'sales', medianUsdRemote: '$88,000', rangeUsdRemote: '$68k–$115k', medianInrIndia: '₹14 LPA', rangeInrIndia: '₹8–22 LPA', topSkills: ['retention', 'onboarding', 'QBRs', 'product adoption', 'escalations'], searchKeywords: ['remote customer success manager', 'remote CSM jobs'] },
  { id: 'project-manager', title: 'Project Manager', category: 'operations', medianUsdRemote: '$98,000', rangeUsdRemote: '$78k–$125k', medianInrIndia: '₹15 LPA', rangeInrIndia: '₹10–24 LPA', topSkills: ['Agile', 'stakeholders', 'risk', 'reporting', 'tools'], searchKeywords: ['remote project manager', 'remote PMO jobs'] },
  { id: 'business-analyst', title: 'Business Analyst', category: 'operations', medianUsdRemote: '$92,000', rangeUsdRemote: '$72k–$118k', medianInrIndia: '₹13 LPA', rangeInrIndia: '₹8–20 LPA', topSkills: ['requirements', 'SQL', 'process mapping', 'documentation', 'workshops'], searchKeywords: ['remote business analyst', 'remote BA jobs'] },
  { id: 'virtual-assistant', title: 'Virtual Assistant', category: 'operations', medianUsdRemote: '$45,000', rangeUsdRemote: '$32k–$60k', medianInrIndia: '₹4 LPA', rangeInrIndia: '₹2.5–7 LPA', topSkills: ['calendar', 'inbox', 'research', 'CRM hygiene', 'booking'], searchKeywords: ['remote virtual assistant', 'remote VA jobs'] },
  { id: 'hr-manager', title: 'HR Manager', category: 'people', medianUsdRemote: '$95,000', rangeUsdRemote: '$75k–$120k', medianInrIndia: '₹14 LPA', rangeInrIndia: '₹9–22 LPA', topSkills: ['policy', 'ER', 'hiring ops', 'compliance', 'culture'], searchKeywords: ['remote HR manager', 'remote people ops jobs'] },
  { id: 'recruiter', title: 'Recruiter', category: 'people', medianUsdRemote: '$82,000', rangeUsdRemote: '$62k–$105k', medianInrIndia: '₹10 LPA', rangeInrIndia: '₹6–16 LPA', topSkills: ['sourcing', 'ATS', 'screening', 'closing', 'employer brand'], searchKeywords: ['remote recruiter', 'remote talent acquisition jobs'] },
  { id: 'finance-manager', title: 'Finance Manager', category: 'finance', medianUsdRemote: '$110,000', rangeUsdRemote: '$88k–$140k', medianInrIndia: '₹18 LPA', rangeInrIndia: '₹12–28 LPA', topSkills: ['FP&A', 'modeling', 'reporting', 'budgets', 'compliance'], searchKeywords: ['remote finance manager', 'remote FP&A jobs'] },
  { id: 'accountant', title: 'Accountant', category: 'finance', medianUsdRemote: '$72,000', rangeUsdRemote: '$55k–$90k', medianInrIndia: '₹8 LPA', rangeInrIndia: '₹5–12 LPA', topSkills: ['bookkeeping', 'QuickBooks', 'tax prep', 'reconciliation', 'payroll'], searchKeywords: ['remote accountant', 'remote bookkeeping jobs'] },
];
