export type JobWorkType = 'remote' | 'hybrid' | 'onsite' | 'unknown';
export type JobSource = 'perplexity' | 'gemini-fallback';

/**
 * A fully enriched, AI-matched daily job.
 * All fields are stored in Firestore so the frontend never needs to call
 * external APIs — everything is shown inline.
 */
export interface DailyJob {
  // ── Identity ────────────────────────────────────────────────────────────────
  id: string;                // fingerprint hash: title::company (stable dedup key)
  fingerprint: string;       // same value, kept explicit for clarity

  // ── Core listing ────────────────────────────────────────────────────────────
  title: string;
  company: string;
  location: string;
  workType: JobWorkType;
  salary: string;            // human-readable string, e.g. "$120k – $160k"

  // ── Full content (stored inline so users never leave the app) ────────────────
  description: string;       // full plain-text job description
  requirements: string[];    // extracted key requirements

  // ── Source metadata ─────────────────────────────────────────────────────────
  source: JobSource;
  applyUrl?: string;         // secondary – shown as "Apply externally" option
  postedAt: string;          // ISO date string
  daysOld?: number;

  // ── AI enrichment (generated by the matching engine) ────────────────────────
  matchScore: number;        // 0–100 relevance score
  finalScore: number;        // composite score (match + freshness + quality)
  matchReasons: string[];    // e.g. "5+ yrs Python matches requirement"
  skillGaps: string[];       // e.g. "No Kubernetes experience in resume"
  aiSummary: string;         // 2–3 sentence AI-written summary of the role
  isHotJob: boolean;         // urgently hiring / fast-growing company
  hotSignals?: string[];     // e.g. ["Series B just closed", "Team doubling"]
  companyStage?: string;     // e.g. "Seed", "Series A", "Public"
  estimatedSalary?: string;  // AI estimate when salary not listed
  matchedCareerPath?: string; // which career path triggered this match
}

/** Lightweight version returned in the daily batch stored on the user doc */
export type DailyJobSummary = Pick<
  DailyJob,
  'id' | 'fingerprint' | 'title' | 'company' | 'location' | 'workType' |
  'salary' | 'matchScore' | 'finalScore' | 'aiSummary' | 'isHotJob' | 'postedAt'
>;

/** Shape stored in users/{uid}/daily_matches/{date} */
export interface DailyMatchRecord {
  userId: string;
  date: string;              // YYYY-MM-DD
  generatedAt: string;       // ISO timestamp
  jobs: DailyJob[];
  jobCount: number;
  sources: Record<JobSource, number>; // how many jobs came from each source
}
