export type CompetitorCategory =
  | 'auto-apply'
  | 'copilot'
  | 'resume'
  | 'job-board'
  | 'interview'
  | 'early-career';

export interface CompetitorMeta {
  id: string;
  name: string;
  website: string;
  category: CompetitorCategory;
  primaryUse: string;
  strengths: string[];
  limitations: string[];
  pricingNote: string;
  bestFor: string;
}

export const COMPETITOR_META: CompetitorMeta[] = [
  {
    id: 'teal',
    name: 'Teal',
    website: 'tealhq.com',
    category: 'copilot',
    primaryUse: 'Job tracker, AI resume builder, and search copilot in one workspace.',
    strengths: ['Clean job tracker UI', 'Resume keyword guidance', 'Chrome extension for saving roles', 'Free tier for basic tracking'],
    limitations: ['Less emphasis on daily validated remote matches', 'You still source and evaluate many listings manually', 'Match scoring is not resume-deep across all workflows'],
    pricingNote: 'Freemium with paid tiers for advanced AI and coaching features.',
    bestFor: 'Candidates who want a visual pipeline and resume tooling in one dashboard.',
  },
  {
    id: 'simplify',
    name: 'Simplify',
    website: 'simplify.jobs',
    category: 'copilot',
    primaryUse: 'Application autofill, job tracker, and copilot for faster form completion.',
    strengths: ['Strong autofill on application portals', 'Large user base and job tracker', 'Useful for high-volume form-heavy applications'],
    limitations: ['Autofill does not replace fit validation', 'Remote-specific filtering varies by source', 'Quality of matches depends on what you browse'],
    pricingNote: 'Free tier with premium for unlimited autofill and advanced features.',
    bestFor: 'Applicants who spend hours on repetitive application forms.',
  },
  {
    id: 'jobscan',
    name: 'Jobscan',
    website: 'jobscan.co',
    category: 'resume',
    primaryUse: 'ATS resume scoring and keyword optimization against job descriptions.',
    strengths: ['Industry-known ATS match score', 'LinkedIn profile optimization', 'Clear keyword gap reports'],
    limitations: ['Does not discover or deliver daily remote jobs', 'Keyword optimization alone does not guarantee recruiter fit', 'Ongoing scans can feel repetitive without a delivery loop'],
    pricingNote: 'Subscription-based scans per month.',
    bestFor: 'Candidates optimizing resume keywords for a role they already found.',
  },
  {
    id: 'careerflow',
    name: 'Careerflow',
    website: 'careerflow.ai',
    category: 'copilot',
    primaryUse: 'AI career copilot with LinkedIn optimization and job search assistance.',
    strengths: ['LinkedIn headline and profile coaching', 'AI-generated application materials', 'Dashboard for search activity'],
    limitations: ['Remote-only validation is not the core wedge', 'Daily match delivery is lighter than dedicated matchers', 'Feature breadth can spread focus away from apply-ready roles'],
    pricingNote: 'Freemium with premium AI credits.',
    bestFor: 'Job seekers who want LinkedIn polish plus general AI writing help.',
  },
  {
    id: 'sonara',
    name: 'Sonara',
    website: 'sonara.ai',
    category: 'auto-apply',
    primaryUse: 'AI agent that searches and applies to jobs on your behalf.',
    strengths: ['Hands-off application volume', 'Automated search and submission loops', 'Appealing for time-starved applicants'],
    limitations: ['Volume apply risks low-fit submissions', 'Recruiters may flag generic auto-applications', 'Less transparent match reasoning per role'],
    pricingNote: 'Subscription for automated apply credits.',
    bestFor: 'Candidates prioritizing application count over match precision.',
  },
  {
    id: 'loopcv',
    name: 'LoopCV',
    website: 'loopcv.pro',
    category: 'auto-apply',
    primaryUse: 'Scheduled auto-apply campaigns to job boards and ATS feeds.',
    strengths: ['Set-and-forget apply campaigns', 'Multiple board integrations', 'Useful for testing market response quickly'],
    limitations: ['Auto-apply without hard validation wastes pipeline slots', 'Remote and timezone rules are easy to miss at scale', 'Reply rates often lag targeted applications'],
    pricingNote: 'Tiered plans by apply volume.',
    bestFor: 'Users comfortable with automated volume-based outreach.',
  },
  {
    id: 'lazyapply',
    name: 'LazyApply',
    website: 'lazyapply.com',
    category: 'auto-apply',
    primaryUse: 'Bulk AI auto-apply to LinkedIn and other platforms.',
    strengths: ['Very high apply throughput', 'Simple campaign setup', 'Popular with spray-and-pray searchers'],
    limitations: ['LinkedIn and platform ToS risk', 'Low personalization at high volume', 'Poor fit for senior or niche remote roles'],
    pricingNote: 'Lifetime and subscription options depending on plan.',
    bestFor: 'Entry-level seekers maximizing application counts.',
  },
  {
    id: 'aiapply',
    name: 'AIApply',
    website: 'aiapply.co',
    category: 'auto-apply',
    primaryUse: 'AI cover letters plus auto-apply workflows.',
    strengths: ['Fast AI-generated cover letters', 'Combined apply automation', 'Low friction onboarding'],
    limitations: ['Generated letters can read templated to recruiters', 'Limited pre-apply validation layer', 'Remote role quality varies by data source'],
    pricingNote: 'Credit-based or monthly subscription.',
    bestFor: 'Applicants who want AI writing plus automated submission.',
  },
  {
    id: 'jobcopilot',
    name: 'JobCopilot',
    website: 'jobcopilot.com',
    category: 'auto-apply',
    primaryUse: 'AI agent positioned to find and apply to matching jobs.',
    strengths: ['Agent-style UX', 'Automated discovery plus apply', 'Minimal daily manual search'],
    limitations: ['Black-box matching can hide why a role fit', 'Auto-apply may not respect nuanced remote constraints', 'Hard to audit application quality at scale'],
    pricingNote: 'Subscription agent plans.',
    bestFor: 'Users who want an AI agent handling search and apply end-to-end.',
  },
  {
    id: 'massive',
    name: 'Massive',
    website: 'massive.ai',
    category: 'auto-apply',
    primaryUse: 'AI-powered job application automation (formerly Hyr).',
    strengths: ['Automation-first positioning', 'Reduced manual apply time', 'Useful for high-volume experiments'],
    limitations: ['Same volume-vs-fit tradeoffs as other auto-appliers', 'Recruiter-side noise from generic applications', 'Less focus on learning from save/dismiss signals'],
    pricingNote: 'Paid automation tiers.',
    bestFor: 'Candidates testing automated application strategies.',
  },
  {
    id: 'wellfound',
    name: 'Wellfound',
    website: 'wellfound.com',
    category: 'job-board',
    primaryUse: 'Startup and tech job board (formerly AngelList Talent).',
    strengths: ['Strong startup and tech catalog', 'Salary and equity transparency on many roles', 'Founder and early-stage company access'],
    limitations: ['You still scroll and self-select listings', 'Remote filters require careful reading', 'No resume-deep daily match delivery'],
    pricingNote: 'Free for candidates; companies pay to post.',
    bestFor: 'Startup-focused candidates browsing curated tech roles.',
  },
  {
    id: 'remote-co',
    name: 'Remote.co',
    website: 'remote.co',
    category: 'job-board',
    primaryUse: 'Remote-only job board and remote work resources.',
    strengths: ['Remote-first listing focus', 'Trusted brand in distributed hiring', 'Company profiles and remote culture content'],
    limitations: ['Manual search and alert setup', 'Listing freshness varies by employer', 'No AI resume scoring pipeline built in'],
    pricingNote: 'Free job search for candidates.',
    bestFor: 'Browsers who want a remote-only board without generalist noise.',
  },
  {
    id: 'flexjobs',
    name: 'FlexJobs',
    website: 'flexjobs.com',
    category: 'job-board',
    primaryUse: 'Curated remote and flexible job listings (subscription board).',
    strengths: ['Hand-screened listings reduce scams', 'Flexible and remote categories', 'Research content on remote work'],
    limitations: ['Paid subscription for full access', 'Curation lag vs direct employer posts', 'You still evaluate fit manually'],
    pricingNote: 'Monthly or annual subscription for candidates.',
    bestFor: 'Candidates willing to pay for vetted flexible job listings.',
  },
  {
    id: 'weworkremotely',
    name: 'We Work Remotely',
    website: 'weworkremotely.com',
    category: 'job-board',
    primaryUse: 'Long-running remote job board across categories.',
    strengths: ['Large remote employer base', 'Simple category browsing', 'Strong brand recognition in remote hiring'],
    limitations: ['Competitive applicant pools on popular roles', 'No personalized match scoring', 'Alerts are keyword-based, not resume-based'],
    pricingNote: 'Free for job seekers.',
    bestFor: 'General remote browsing across engineering, marketing, and ops.',
  },
  {
    id: 'remotive',
    name: 'Remotive',
    website: 'remotive.com',
    category: 'job-board',
    primaryUse: 'Remote jobs plus community and newsletter distribution.',
    strengths: ['Active remote community', 'Newsletter reach for new roles', 'Category filters for function and region'],
    limitations: ['Discovery is still listing-centric', 'Premium tiers for some features', 'Match quality depends on your filtering discipline'],
    pricingNote: 'Free search; optional paid community or resources.',
    bestFor: 'Remote workers who like community plus job listings together.',
  },
  {
    id: 'remoteok',
    name: 'Remote OK',
    website: 'remoteok.com',
    category: 'job-board',
    primaryUse: 'High-volume remote job aggregator with salary tags.',
    strengths: ['Huge remote listing volume', 'Salary tags on many posts', 'Fast daily refresh'],
    limitations: ['Syndicated duplicates across sources', 'Signal-to-noise ratio requires heavy filtering', 'No application workflow or resume tailoring'],
    pricingNote: 'Free search; employers pay to promote posts.',
    bestFor: 'Power browsers who filter aggressively by salary and stack.',
  },
  {
    id: 'arc-dev',
    name: 'Arc.dev',
    website: 'arc.dev',
    category: 'job-board',
    primaryUse: 'Remote developer hiring marketplace and job listings.',
    strengths: ['Developer-specific remote focus', 'Talent network and vetting layers', 'International remote opportunities'],
    limitations: ['Primarily engineering-centric', 'Profile setup before strong matches', 'Less suited for PM, design, or marketing roles'],
    pricingNote: 'Free candidate profiles; companies pay to hire.',
    bestFor: 'Remote software engineers building a public talent profile.',
  },
  {
    id: 'otta',
    name: 'Otta',
    website: 'otta.com',
    category: 'job-board',
    primaryUse: 'Personalized job recommendations with company insights.',
    strengths: ['Clean UX and company context', 'Curated recommendations', 'Useful startup and scale-up coverage'],
    limitations: ['Geography and remote filters vary by market', 'Recommendations are not full resume parsing pipelines', 'Less apply automation built in'],
    pricingNote: 'Free for candidates.',
    bestFor: 'Candidates who want curated picks with company research.',
  },
  {
    id: 'himalayas',
    name: 'Himalayas',
    website: 'himalayas.app',
    category: 'job-board',
    primaryUse: 'Remote job board with company profiles and salary data.',
    strengths: ['Modern remote board UX', 'Company remote profiles', 'Salary and benefit filters'],
    limitations: ['Still a browse-and-apply model', 'No daily resume-grounded Scout delivery', 'Competitive roles fill quickly without alerts'],
    pricingNote: 'Free for job seekers.',
    bestFor: 'Remote candidates who research companies while browsing roles.',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    website: 'linkedin.com/jobs',
    category: 'job-board',
    primaryUse: 'Default professional network and job search platform globally.',
    strengths: ['Largest recruiter presence', 'Easy Apply on many roles', 'Network effects for referrals and InMail'],
    limitations: ['Remote filters are noisy and often mis-tagged', 'Easy Apply encourages low-effort volume', 'Generic alerts lack resume-deep ranking'],
    pricingNote: 'Free job search; Premium optional for insights and InMail.',
    bestFor: 'Everyone — but rarely sufficient alone for focused remote search.',
  },
  {
    id: 'indeed',
    name: 'Indeed',
    website: 'indeed.com',
    category: 'job-board',
    primaryUse: 'Largest general job aggregator worldwide.',
    strengths: ['Massive listing volume', 'Simple search and alerts', 'Salary and review integrations'],
    limitations: ['Remote tags are frequently inaccurate', 'Duplicate and expired listings', 'High competition without tailoring'],
    pricingNote: 'Free for candidates.',
    bestFor: 'Broad market scanning across industries and locations.',
  },
  {
    id: 'glassdoor',
    name: 'Glassdoor',
    website: 'glassdoor.com',
    category: 'job-board',
    primaryUse: 'Jobs plus company reviews and salary reports.',
    strengths: ['Rich company review data', 'Salary self-reports by role', 'Interview experience crowdsourcing'],
    limitations: ['Job listings secondary to reviews', 'Remote filtering inconsistent', 'No match-first daily delivery'],
    pricingNote: 'Free with optional premium insights.',
    bestFor: 'Researchers comparing culture and compensation before applying.',
  },
  {
    id: 'handshake',
    name: 'Handshake',
    website: 'joinhandshake.com',
    category: 'early-career',
    primaryUse: 'University recruiting platform for students and recent grads.',
    strengths: ['Strong campus and early-career employer base', 'Event and fair integrations', 'Employer messaging to students'],
    limitations: ['Limited for experienced remote professionals', 'Geography tied to school networks', 'Not built for daily AI remote matching'],
    pricingNote: 'Free for students via partner schools.',
    bestFor: 'Students and new grads entering the job market.',
  },
  {
    id: 'rezi',
    name: 'Rezi',
    website: 'rezi.ai',
    category: 'resume',
    primaryUse: 'AI resume builder optimized for ATS formatting.',
    strengths: ['ATS-friendly templates', 'AI bullet generation', 'Resume scoring feedback'],
    limitations: ['No job discovery or daily match delivery', 'Resume tool only — search is elsewhere', 'Templates can resemble other AI resumes'],
    pricingNote: 'Freemium with paid Pro builder features.',
    bestFor: 'Candidates rebuilding a resume document from scratch.',
  },
  {
    id: 'final-round-ai',
    name: 'Final Round AI',
    website: 'finalroundai.com',
    category: 'interview',
    primaryUse: 'Live interview copilot and prep tools.',
    strengths: ['Real-time interview assistance', 'Mock interview flows', 'Popular with active interview cycles'],
    limitations: ['Focused on interview stage, not job discovery', 'Ethical and employer-policy considerations', 'Does not replace a remote job pipeline'],
    pricingNote: 'Subscription for copilot and prep features.',
    bestFor: 'Candidates already in live interview processes.',
  },
];
